### ISSUE TITLE
different Middleware::Logging classes

### ISSUE THREAD

**Issue by dmcclory** [tweag/stacker_bee#23]
Hey all,

@mattmcmanus and I tried to use StackerBee with gelf-rb's logger. We hit two problems, I'll describe the larger issue here.

when StackerBee writes to the logger, it calls multiple logger methods. It would be better to have all of the information in one GrayLog event. This is happening in StackerBee::Middleware::Logger.

We could either change the Middleware::Logger so that it only writes one method, or we could make it possible to supply your own Middleware::Logger class (in addition to your own logger)

Thoughts?

(I prefer the second approach)

**Comment by nicholaides** [comment]
This will be fixed by #26
