### ISSUE TITLE
Overridable endpoints

### ISSUE THREAD

**Issue by nicholaides** [tweag/stacker_bee#3]
Applications should be able to add/modify endpoints. It's possible that CloudStack's documentation is wrong, or that users might set up proxies to CloudStack that work slightly differently that CloudStack itself.

**Comment by gsterndale** [comment]
The API is configurable in that you can specify a file containing a JSON description of the API. Does this suffice?

**Comment by nicholaides** [comment]
I'm not sure. I think we should revisit this when the need arrises.
