### ISSUE TITLE
Replace StackerBee::Rash with Hashie::Rash?

### ISSUE THREAD

**Issue by nicholaides** [tweag/stacker_bee#30]
https://github.com/tcocca/rash

Would we be able to replace StackerBee::Rash with Hashie::Rash? If so, it would remove some tests that we would need to support.

**Comment by justincampbell** [comment]
@nicholaides Just swapping it out doesn't yield the same behavior. I didn't spend a lot of time inspecting the differences.  We could update our usage to match the different behavior...

If our implementation seems solid, I don't know if it's worth it.
