### ISSUE TITLE
acceptance tests for bin/stacker_bee

### ISSUE THREAD

**Issue by dmcclory** [tweag/stacker_bee#55]
stacker_bee's executable has broken a few times. We should have a test or two to exercise it.

We could use [Aruba](https://github.com/cucumber/aruba) or possibly [Bats](https://github.com/sstephenson/bats) to drive the cli.

**Comment by nicholaides** [comment]
As @justincampbell suggested, we should have a `StackerBee::CLI` object to which the executable can delegate. That object can be tested just like any other object. Then, the tests for the executable can be minimal.
