### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by sebgoa** [tweag/stacker_bee#59]
Hi I am getting SSL verification errors when using an https endpoint.
Is it supposed to work with https ?

**Comment by nicholaides** [comment]
In some environments we turned off SSL certificate verification via the `ssl_verify` option:

```
StackerBee::Client.configuration = {
  ssl_verify: false,
  # ...
}
```

@dgrizzanti do you remember why we turn it off?

**Comment by nicholaides** [comment]
I added some documentation about SSL and the `ssl_verify` option: 059fc41263d429e9deba6e5619af6f214e80df11
